import { useState } from 'react';

export default function CreateCourse() {
    const [courseData, setCourseData] = useState({
        name: '',
        code: '',
        description: '',
    });

    function handleChange(e) {
        const { name, value } = e.target;
        setCourseData((prev) => ({
            ...prev,
            [name]: value
        }));
    }

    async function handleSubmit(e) {
        e.preventDefault();

        const course = {
            id: crypto.randomUUID(), // change later to be generated by the backend
            name: courseData.name.trim(),
            code: courseData.code.trim(),
            description: courseData.description.trim(),
            image: null, // add image upload functionality later
        };

        try {
            const response = await fetch('http://localhost:3000/api/courses', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(course),
            });

            if (!response.ok) {
                throw new Error('Failed to create course');
            }

            const createdCourse = await response.json();
            console.log('Created course:', createdCourse);

            setCourseData({
                name: '',
                code: '',
                description: '',
            });
        } catch (error) {
            console.error('Error creating course:', error);
        }
    }

    return (
        <div>
            <form onSubmit={handleSubmit}>
                <legend>What is your course?</legend>
                <p>Describe your course to help people find it.</p>
                <fieldset>
                    <label htmlFor="name">Course Name:</label>
                    <input
                        type="text"
                        id="name"
                        name="name"
                        value={courseData.name}
                        onChange={handleChange}
                        required
                    />
                </fieldset>
                <fieldset>
                    <label htmlFor="code">Course Code:</label>
                    <input
                        type="text"
                        id="code"
                        name="code"
                        value={courseData.code}
                        onChange={handleChange}
                        required
                    />
                </fieldset>
                <fieldset>
                    <label htmlFor="description">Course Description:</label>
                    <textarea
                        id="description"
                        name="description"
                        value={courseData.description}
                        onChange={handleChange}
                        required 
                    />
                </fieldset>
                <button type="submit">Create Course</button>
            </form>
        </div>
    );
}